### ISSUE TITLE
ATTDEF problem

### ISSUE THREAD

**Issue by fiorefrank** [vagran/dxf-viewer#48]
I have a dxf with some ATTDEF  object and the vewer doesn't load dxf at alll.
In the console there is "Unhandled entity type: ATTDEF".

how can i fix it?

**Comment by kimkanghyune** [comment]
#46 Currently, that feature is not complete. Please give your opinion in this pull request.

**Comment by vagran** [comment]
@fiorefrank Actually particular unhandled entity should not prevent your DXF from being loaded. What is the full console dump? Is it possible to get your example file for investigation?

**Comment by terroj** [comment]
I've the same problem

There is my file: https://www.file.io/UFLS/download/DqJQoxzJkn4l

console log: 
```
DxfScene.js:332 Unhandled entity type: ATTDEF
DxfScene.js:332 Unhandled entity type: ATTDEF
DxfScene.js:332 Unhandled entity type: ATTDEF
DxfScene.js:332 Unhandled entity type: ATTDEF
DxfScene.js:332 Unhandled entity type: ATTDEF
DxfScene.js:332 Unhandled entity type: ATTDEF
DxfScene.js:332 Unhandled entity type: ATTDEF
DxfScene.js:332 Unhandled entity type: ATTDEF
DxfScene.js:332 Unhandled entity type: ATTDEF
DxfScene.js:332 Unhandled entity type: ATTDEF
DxfScene.js:332 Unhandled entity type: ATTDEF

DxfScene.js:1414 Unresolved nested block reference: *U
_ProcessInsert @ DxfScene.js:1414
_ProcessDxfEntity @ DxfScene.js:308
Build @ DxfScene.js:175
await in Build (async)
_Load @ DxfWorker.js:159
await in _Load (async)
_ProcessRequestMessage @ DxfWorker.js:80
_ProcessRequest @ DxfWorker.js:64

DxfWorker.js:66 TypeError: Cannot read properties of undefined (reading 'RegisterNestedUse')
    at nm.NestedBlockContext (DxfScene.js:2454:15)
    at $f._ProcessInsert (DxfScene.js:1416:40)
    at $f._ProcessDxfEntity (DxfScene.js:308:18)
    at $f.Build (DxfScene.js:175:26)
    at async um._Load (DxfWorker.js:160:9)
    at async um._ProcessRequestMessage (DxfWorker.js:80:27)
    at async um._ProcessRequest (DxfWorker.js:64:18)
_ProcessRequest @ DxfWorker.js:66
```

**Comment by vagran** [comment]
Download link does not work for me:
![image](https://github.com/vagran/dxf-viewer/assets/6065976/cb85812b-e2bf-4296-a0da-82ad99e8e573)

**Comment by terroj** [comment]
> Download link does not work for me: ![image](https://user-images.githubusercontent.com/6065976/248780037-cb85812b-e2bf-4296-a0da-82ad99e8e573.png)

https://drive.google.com/file/d/1g2zzLa31_fXrN94NmBVGIYy-NJUqNff_/view?usp=sharing

**Comment by vagran** [comment]
> https://drive.google.com/file/d/1g2zzLa31_fXrN94NmBVGIYy-NJUqNff_/view?usp=sharing

Issues with your sample file are fixed and included in just released version `1.0.28`. The problem was not related to this issue, it is about unresolved block references handling. Also the file contains `SPLINE` entity which is defined by fit points which is not yet implemented (mostly because of lack of sample files), will check it later. For now some spline in this file is just not displayed. BTW Autodesk online viewer also reports some problems with the file, and limits the functionality of the viewer when displaying it.
